// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLzL5YfDygjsM2mVCKPCdhgW3FAgZnozc',
    appId: '1:778134681477:web:5b805903a48dc312d136ec',
    messagingSenderId: '778134681477',
    projectId: 'chat-app-6840f',
    authDomain: 'chat-app-6840f.firebaseapp.com',
    storageBucket: 'chat-app-6840f.firebasestorage.app',
    measurementId: 'G-HBE3CCJ40K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATHLHZqmxkGoL2anBrgBMBIS_id0GnO0Q',
    appId: '1:778134681477:android:8964633a22ca6327d136ec',
    messagingSenderId: '778134681477',
    projectId: 'chat-app-6840f',
    storageBucket: 'chat-app-6840f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPnZh_GYMRnRjdd0auPiEz30taCBgNnHw',
    appId: '1:778134681477:ios:bf064a2268f5bbb5d136ec',
    messagingSenderId: '778134681477',
    projectId: 'chat-app-6840f',
    storageBucket: 'chat-app-6840f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPnZh_GYMRnRjdd0auPiEz30taCBgNnHw',
    appId: '1:778134681477:ios:bf064a2268f5bbb5d136ec',
    messagingSenderId: '778134681477',
    projectId: 'chat-app-6840f',
    storageBucket: 'chat-app-6840f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLzL5YfDygjsM2mVCKPCdhgW3FAgZnozc',
    appId: '1:778134681477:web:4021994d39bb2558d136ec',
    messagingSenderId: '778134681477',
    projectId: 'chat-app-6840f',
    authDomain: 'chat-app-6840f.firebaseapp.com',
    storageBucket: 'chat-app-6840f.firebasestorage.app',
    measurementId: 'G-25BLD1KVTE',
  );
}
